apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  clusterIP: None
  ports:
    - name: cql
      port: 9042
  selector:
    app: cassandra
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 4
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: cassandra
      containers:
      - env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 512M
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        image: merapar/cassandra:2.3
        name: cassandra
        volumeMounts:
          - mountPath: /cassandra-storage
            name: cassandra-storage
  volumeClaimTemplates:
  - metadata:
      name: cassandra-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
